# Generated by Django 5.2.5 on 2025-10-15 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите полное имя сотрудника",
                        max_length=200,
                        verbose_name="ФИО сотрудника",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("junior", "Младший разработчик"),
                            ("middle", "Разработчик"),
                            ("senior", "Старший разработчик"),
                            ("team_lead", "Тимлид"),
                            ("manager", "Менеджер"),
                            ("analyst", "Аналитик"),
                            ("tester", "Тестировщик"),
                        ],
                        help_text="Выберите должность сотрудника",
                        max_length=50,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Введите email сотрудника",
                        max_length=100,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Укажите дату приема на работу",
                        verbose_name="Дата приема на работу",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="api_employe_full_na_fcfed5_idx"
                    ),
                    models.Index(
                        fields=["position"], name="api_employe_positio_a8b669_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название задачи",
                        max_length=200,
                        verbose_name="Наименование задачи",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Укажите срок выполнения задачи",
                        verbose_name="Срок выполнения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "К выполнению"),
                            ("in_progress", "В работе"),
                            ("in_review", "На проверке"),
                            ("done", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="todo",
                        help_text="Выберите статус задачи",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительное описание задачи",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        help_text="Выберите приоритет задачи",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        help_text="Выберите исполнителя задачи",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите родительскую задачу, если есть зависимость",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="api.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="api_task_status_2aef03_idx"),
                    models.Index(
                        fields=["due_date"], name="api_task_due_dat_54ead5_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="api_task_priorit_175238_idx"
                    ),
                    models.Index(
                        fields=["assignee", "status"],
                        name="api_task_assigne_b09f5a_idx",
                    ),
                ],
            },
        ),
    ]
